#!/bin/sh
#deploy="false"
deploy="true"

image=UserMP
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t salisaurabh/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push salisaurabh/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag salisaurabh/${image}:1.0-SNAPSHOT salisaurabh/${image}:latest
        docker push salisaurabh/${image}:latest
    fi
fi